// catch any errors that may be rthrown inside async fn route handlers
module.exports = (func) => {
  return (req, res, next) => {
    func(req, res, next).catch(next);
  };
};
